// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtfycPbETnvGmBlfvTHK7F1QE3IVFlQ_s',
    appId: '1:237481545433:web:083c7f977abdc203a4b8c8',
    messagingSenderId: '237481545433',
    projectId: 'tefillin-7f1b5',
    authDomain: 'tefillin-7f1b5.firebaseapp.com',
    storageBucket: 'tefillin-7f1b5.appspot.com',
    measurementId: 'G-0GFQQ5GVRB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF3WlWTB5eMzvmQ4wxtWakANfGoYc7Bfs',
    appId: '1:237481545433:android:0b7cf6174cfaab2ea4b8c8',
    messagingSenderId: '237481545433',
    projectId: 'tefillin-7f1b5',
    storageBucket: 'tefillin-7f1b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhDymuFaADHoLR19CBClXYUpoarbt7iSg',
    appId: '1:237481545433:ios:73ff4d2cb5f8d260a4b8c8',
    messagingSenderId: '237481545433',
    projectId: 'tefillin-7f1b5',
    storageBucket: 'tefillin-7f1b5.appspot.com',
    iosClientId: '237481545433-sn5h9tf5efji267suhvopmld26dqhat3.apps.googleusercontent.com',
    iosBundleId: 'com.example.tefillin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhDymuFaADHoLR19CBClXYUpoarbt7iSg',
    appId: '1:237481545433:ios:73ff4d2cb5f8d260a4b8c8',
    messagingSenderId: '237481545433',
    projectId: 'tefillin-7f1b5',
    storageBucket: 'tefillin-7f1b5.appspot.com',
    iosClientId: '237481545433-sn5h9tf5efji267suhvopmld26dqhat3.apps.googleusercontent.com',
    iosBundleId: 'com.example.tefillin',
  );
}
